<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>StardewModdingAPI.Toolkit.CoreInterfaces</AssemblyName>
    <RootNamespace>StardewModdingAPI</RootNamespace>
    <Version>4.5.2</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsTrimmable>false</IsTrimmable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
